### PR TITLE
Localization 1st fix

### PR DESCRIPTION
**Pull request by manolisvasilakis**
Robot_localization seems to be working, need to add camera odom data at config file

### CODE REVIEW

**Comment by stasinos** [comment]
Please explain was not working and what you did to fix it

**Comment by manolisvasilakis** [comment]
At ekf_localization.yaml, odom0_differential should be false, since gps is used for position and not velocity.
At ekf_localization.yaml, imu0_config Y_acceleration should be false, the robot will not undergo instantaneous Y acceleration. However, the IMU will likely report non-zero, noisy values for Y acceleration, which can cause the estimate to drift rapidly. (http://docs.ros.org/melodic/api/robot_localization/html/configuring_robot_localization.html)

**Comment by stasinos** [comment]
How is "Added trivial rtabmap support for visual odometry" related to the localization fix? I feel this should be a different PR.

**Comment by gstavrinos** [comment]
We need to speak with Manolis about how PRs work. (And other general guidelines, like writing (greek) comments inside files.)

**Pull request closed without merging**
